# [[plugins]]
# repo = 'nosami/Omnisharp'
# on_ft = ['cs']
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'MSBuild.exe server/OmniSharp.sln /p:Platform="Any CPU"'
#   else
#     let cmd = 'xbuild server/OmniSharp.sln'
#   endif
#   let g:dein#plugin.build = cmd
# '''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'joonty/vdebug'
on_ft = 'php'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['ruby', 'go']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = 'go'
on_i = 1
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#snippets_directory='~/.vim//snippets/'
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'

# markdownのプレビュー
# http://dackdive.hateblo.jp/entry/2014/09/11/213455

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
depends = ['previm', 'open-browser.vim']

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'mattn/benchvimrc-vim'
on_cmd = ['BenchVimrc']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'toyamarinyon/vim-swift'
if   = '''has('mac')'''
on_ft = 'swift'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

