[[plugins]]
repo = 'tacroe/unite-mark'
on_source = 'unite.vim'

[[plugins]]
repo = 'nosami/Omnisharp'
on_ft = ['cs']
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'MSBuild.exe server/OmniSharp.sln /p:Platform="Any CPU"'
  else
    let cmd = 'xbuild server/OmniSharp.sln'
  endif
  let g:dein#plugin.build = cmd
'''
