####################################################################
# vim / neovim

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if has('win32')
    let cmd = 'tools\\update-dll-mingw'
  elseif has('win32unix')
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# [[plugins]]
# repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'Yggdroot/indentLine'

# [[plugins]]
# repo = 'thinca/vim-quickrun'
# 
# [[plugins]]
# repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'simeji/winresizer'

# [[plugins]]
# repo = 'vim-scripts/delek.vim'
# 
# [[plugins]]
# repo = 'tomasr/molokai'
# 
# [[plugins]]
# repo = 'sjl/badwolf'
# 
# [[plugins]]
# repo = 'dracula/vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# [[plugins]]
# repo = 'pocari/neovim-rplugin-ruby-sample'

[[plugins]]
repo = 'rhysd/vim-color-spring-night'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

####################################################################
# neovim only

[[plugins]]
# nvim で矩形ペーストが動かない件の対策直ったら不要
if = 'has("nvim")'
repo = 'bfredl/nvim-miniyank'
hook_add = '''
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
'''

####################################################################
# vim only
[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua") && !has("nvim")'
on_i = 1

[[plugins]]
if = '!has("nvim")'
repo = 'kana/vim-fakeclip'

[[plugins]]
if = '!has("nvim")'
repo = 'tpope/vim-dispatch'

[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/neomru.vim'

[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/neoyank.vim'

# [[plugins]]
# repo = 'kien/ctrlp.vim'

# [[plugins]]
# # # cpsm/install.shのcmakeへの環境変数に
# # https://github.com/pocari/cpsm/commit/67ff63031e5b7413147464aee48463e831b67287
# # の変更を行うとうまくbuildできる。なんかいい方法ある？？
# # とりあえずforkして対応
# repo = 'pocari/cpsm'
# rev = 'fix-python-path'
# hook_post_update = '''
#   let g:dein#plugin.build = 'sh -c "PY3=ON ./install.sh"'
# '''

[[plugins]]
if = '!has("nvim")'
repo = 'vim-jp/vital.vim'

# [[plugins]]
# repo = 'justinmk/vim-dirvish'

