[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua") && !has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kana/vim-fakeclip'

# [[plugins]]
# repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'BufOnly.vim'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = "thinca/vim-qfreplace"

[[plugins]]
repo = 'vim-scripts/gtags.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'kovisoft/slimv'
if   = '''! has('mac')'''

[[plugins]]
repo = 'toyamarinyon/vim-swift'
if   = '''! has('mac')'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'kien/ctrlp.vim'

[[plugins]]
# # cpsm/install.shのcmakeへの環境変数に
# https://github.com/pocari/cpsm/commit/67ff63031e5b7413147464aee48463e831b67287
# の変更を行うとうまくbuildできる。なんかいい方法ある？？
# とりあえずforkして対応
repo = 'pocari/cpsm'
rev = 'fix-python-path'
hook_post_update = '''
  let g:dein#plugin.build = 'sh -c "PY3=ON ./install.sh"'
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
