[[plugins]]
repo = 'tacroe/unite-mark'
on_source = 'unite.vim'

# [[plugins]]
# repo = 'nosami/Omnisharp'
# on_ft = ['cs']
# hook_post_update = '''
#   if dein#util#_is_windows()
#     let cmd = 'MSBuild.exe server/OmniSharp.sln /p:Platform="Any CPU"'
#   else
#     let cmd = 'xbuild server/OmniSharp.sln'
#   endif
#   let g:dein#plugin.build = cmd
# '''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'joonty/vdebug'
on_ft = 'php'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['ruby', 'go']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-go'
if = 'has("nvim")'
on_ft = 'go'
on_i = 1
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#snippets_directory='~/.vim//snippets/'
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
