####################################################################
# vim / neovim

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'vim-scripts/delek.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

# [[plugins]]
# repo = 'w0rp/ale'

[[plugins]]
# macvim用
if = '!has("nvim")'
repo = 'rhysd/vim-color-spring-night'
merged = 0

[[plugins]]
if = 'has("nvim")'
repo = 'Shougo/defx.nvim'

####################################################################
# neovim only

[[plugins]]
# nvim で矩形ペーストが動かない件の対策直ったら不要
# https://github.com/neovim/neovim/issues/1822
if = 'has("nvim")'
repo = 'bfredl/nvim-miniyank'
hook_add = '''
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
'''

####################################################################
# vim only
[[plugins]]
if = '!has("nvim")'
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if has('win32')
    let cmd = 'tools\\update-dll-mingw'
  elseif has('win32unix')
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua") && !has("nvim")'
on_i = 1

[[plugins]]
if = '!has("nvim")'
repo = 'kana/vim-fakeclip'

[[plugins]]
if = '!has("nvim")'
repo = 'tpope/vim-dispatch'

[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/neomru.vim'

[[plugins]]
if = 'has("lua") && !has("nvim")'
repo = 'Shougo/neoyank.vim'

# [[plugins]]
# repo = 'kien/ctrlp.vim'

# [[plugins]]
# # # cpsm/install.shのcmakeへの環境変数に
# # https://github.com/pocari/cpsm/commit/67ff63031e5b7413147464aee48463e831b67287
# # の変更を行うとうまくbuildできる。なんかいい方法ある？？
# # とりあえずforkして対応
# repo = 'pocari/cpsm'
# rev = 'fix-python-path'
# hook_post_update = '''
#   let g:dein#plugin.build = 'sh -c "PY3=ON ./install.sh"'
# '''

[[plugins]]
if = '!has("nvim")'
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'rhysd/git-messenger.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'natebosch/vim-lsc'

# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-python'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# 
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# 
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-neosnippet.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'

[[plugins]]
repo = 'tyru/current-func-info.vim'

# [[plugins]]
# repo = 'thinca/vim-quickrun'

